language: node_js
node_js:
- stable
addons:
  code_climate:
    repo_token:
      secure: PonAS8p4Hk2bfbRPRnvGkGH5rQcZwTrKxfCfQytTCXgkDfZgTbMuQMDX1l5KDGobbZUFleKQN2Vds7YPBxg7HRpobfX+j8+2s78LIY5YAignexP4FKsWEcKWpEqtCzIXrnKPrZp1cHCYBjS4y3iB+DS8u9x+2X22Swx6riE4ByMoD/AbjgmEK1wjO5NWKlmOviqCsuWHl2FPdDXcEaS7/qImVHjV9u5KhTt4gsOtUgVYjvMnoiDythoyDIH1shdjl25RtfmwqYIMzfs/xlZjqWGofOeuWhe6RAfBBr0PBs2W/bYZbGFVu2GcygoP3jQhRuQGCJA+hcr0BugxAH7/JZyYS0eJ7EIlsFCsPpxdARiA5qvP0Y+E+6Sl/21WxyhGMjTCLcPSG9z6xsmhKHC2Rolhe29qwxPoBV88DjLdLXnctu8mHn0xcsLU1Vxvx6xYjzTYmIsFv0rWgabXSudZJltoz+QqYBJtcqRrBA0wXA5p6Owto/2sr2SeOvtL0vLKGKp6nMOlXFtBZzKOY7TGaPZAsqLktl+D9niGpT9I1Z6ZDjqvlJ3eBd2WqU9Tf4l2BFaQWwDbeoJfSR6INNZkU8paQnnuDWADl1LqXKT1DyCDWguq1cargbprMmBjf3KGmPqzP4wPOndRAftZ8O1wnKw3MuLiuxedHfM6Sfnrd3E=
before_script:
- yarn setup
- yarn build
- yarn global add codeclimate-test-reporter
script:
- yarn coverage
after_success:
- npm pack
after_script:
- codeclimate-test-reporter < ./coverage/lcov.info
deploy:
  provider: npm
  email: rgoyard@gmail.com
  api_key:
    secure: XWljUYmvYAqYEwH1EJlc4to8GJj+hkFzZTHSMOKmi9ByxbEU4v4KP9t6S31euanVKsDO3wlMhyqOTk5NB51qfuNlXa5pIBs2P2vPgqpN+3tDGfLkUcM319NXd3cgJIcCzlvxJMBjz9wGfG8UnhkX/8wuSVLf8LmL7/ex9OJfl5WkQs6n9BV72Ty1AH9RU1tkJDUaBhIrEDFG+7nytycpGETAfgNSHbs7ui5Knb61k1BGlA1lUIA/3RAwoT1SRXeZ1yQJ+TcByP2npRE7mMso083iDFLL9Jyns5VLhbfEi9TK+DIIEh5xYnp+1e+cikoVue4+LyD7LxRhG9/RuiRCzLuWW02yNJoenxvbDgbGHhDAMkCDLifhsWWd4b/CF/665i0BqiYxkrXTbxb7bBGbryBz2djv//CuVZdoxqcZnLT8uBI2Yr5oC2glU/s6KmyvacRedQPD81bq9vcDRTfzo57kgGWFFwPvY1ckROUz/WQiykBu8KUPBoOwCO0Bl+YSFNyTOHX/Z1wpdkOQ9CaZX2/tfVEzqmHoAq+ngHN8RF+oBagekFtOT/CzO5NiqMX/qQo3ZBlWOjMjSA9UyOsGKVMPKVr7ydPcdC1dI+iE/Imf4m54x22F5QAcSr5Nq+xgG0luIQffskEAzgK81cHRFo7iz2CJQEPVSjqAz0LuYTc=
  on:
    tags: true
    repo: mimiz/nodejs-event-manager
