language: node_js
node_js:
- stable
addons:
  code_climate:
    repo_token:
      secure: ar0d/iZAZbqD4+2UAchyO7G5uax8F2fF4cutyAsA2dsLEHxeGh8SUifksN+1/MtlNgPcxJ0W9wFHMWTZlD/U1fFkPJ7AtzjrDY/tRNT1qDMR/kpFg0/0CDBrs5v9Mx3/BZqxJ+XeTyxB7nhGIo+l+CIHJ+SwuPE16dU+J0vzKYrW+gwxnl9Qo6lu03mSDkmUreejYESC+t3HlQgtw4PjCqrv1rx2covzoLMcVP2tH1i/Ry308HUCLCDiaKk8CDUJRSPR0P3TpHJ4dSyMFqjVNfKuqC92a+LyvocV8c1x1frMqB+SJGEEHMej19C9QrSfUb6fHd4cEjXloulqzja+M7MGvXDF7+lp+4rTy5Cg2mqjwKaKA0+P5n9Um7vexY0yEZUblxIjMklPC65p3LZJlzoEX2IjXPVtpWIUB/sbNCgWFD/lOURTRd4u87U745JVzZFttJ5FErnnVQNaWIBgMVXlTBnwCkakKGrq8iUZZZlCaA5r41P/Qo2uw2WitraAQGhCJIloGhaMAFr+ajWyrdWjuGnLaa4HJNlI2UGYRLyNQSGlzgB1bKSr+sqgLRyk8AOGjP8SeNOupYeX6+YEN+CXU7plHb9T9z3U/ZjPhBw4z80LAIyenw/D4LD7lCD0CReYjAJfpZ57nzyPllMsBIkfm01oQgD1I6yTXSOPsXE=
before_script:
- yarn setup
- yarn build
- yarn global add codeclimate-test-reporter
script:
- yarn coverage
after_success:
- npm pack
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
deploy:
  - provider: releases
    api_key:
      secure: GbLEaCnME+AErqwr6/byM1ffow27jv1mxdlO5y6bE/DkUVvzdDOmJ+5qYaFMXGfMynTgOXJ9KWzMOw918tLD/rDJ3iR4CsZ5+cuPVjG9y19xZjRklFDtYKlqohlbRm4418hFN9zNFcfhU+C9c0s7c0hHI8VWBzR+L2xeu/OcqP7+VgzkKCLXk5S0rFVmT4iWJWtvca8flnXg+fUFZgIthlnILCnavqOqmkn+YTAA8L9Lv3LPtxvVy7vsyKPPEXGAG9fK+NqJkGSgtjEChN+afzBkAVpCpYb/Sjzxz+TcH7ztAhe5FIMqYehqfP1LfdDQRdENyZhxVhSUSQEWxea7kDxG9UfQAd6vy3B9T1rhS+tFEp79x912U7FXLaxQeT7w/67ngL3qCr1UrsE7zbMEL7ModLsuk5X6ALIqG+KyGupZV1mBjAui9kQ7ZgZMC+qxS7QnajiakdMYSCXRCkQgdZuSabxrOUIHCpptOq9AjECK6SCMXwon69B9YWnI8lzFdztS127bBFAdwvF9c0d1ThNAtcX+xRzzRajKLdIIu2tCnmOnMFbJFD4ZxEE813yQ+O9KbmEn1em53XgDaOpzi9t1LtemSjr1yJBL4Pn+7SJg/bQ7QwITNf2NUmDeYy9wv7xM/zbFQ/pnM65Kz//bAI6JHIVmD/OpmfyDgzUIA8M=
    file: nodejs-event-manager-*.tgz
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: 
      secure: nDNoR3sktWF6SrZJdoDkzUVbw55h9uEK22VfUqGWzAr366YP9mBq5edJ2SNPJmKGsdlP5SGlgwCaWw0rMRt+Rpk2+CpTXKgwgw7mV0ddR59yM39TAev9gUJwPEmeC79YFPjF4IOeeoVXXGjO3e4ZhjvCIhHt1S2AS3TKrBP27w3zjz8wk0sfhcVN2yc473bsWUrdtoSnWXJMB8yRHGsFdp435IVa98Q+a2YSsq6+V/hhMmYNAxZD+y7AYW1l/96i8AbfKRkkrrBnbRezHDcCPO0YG45S4sDooXi1grgIqmcAGnK8cUsgKCHFRd2QkADZjwGVPorywwfIcctp5O/iVcCP5Ah3g2RMDuJn1x5ZuvgtS2KBtSaGJJQPD9XjjILPCP9w9lAsAjUdUd8viJPdDAe88Rsmn8RLuKdIwZFuVNE5Yk4DgjuTYGVSDEgWbl28txpZJtb2t3POkVOSt9CuzWKtEUN/m1VxSzlx6m/VyyrL27qpKEWQ1Bcp8YsdwDHzU85So7SrrvWUfNqdExaB3WvOg9OWUqqnvxJr8aXf14CfFzBtEdsWmcjMLlb/ISE36iDymzRINWAIQ/MJ0DiGwrbKD/Q0CJrqhb+80vpYnV5c9ni+oqHBP1QdsYmusMMKC8xrgWckjCehJM++0CoLvfsk/8xVmkhRMzR/++P+TW8=
    skip_cleanup: true
    api_key:
      secure: XWljUYmvYAqYEwH1EJlc4to8GJj+hkFzZTHSMOKmi9ByxbEU4v4KP9t6S31euanVKsDO3wlMhyqOTk5NB51qfuNlXa5pIBs2P2vPgqpN+3tDGfLkUcM319NXd3cgJIcCzlvxJMBjz9wGfG8UnhkX/8wuSVLf8LmL7/ex9OJfl5WkQs6n9BV72Ty1AH9RU1tkJDUaBhIrEDFG+7nytycpGETAfgNSHbs7ui5Knb61k1BGlA1lUIA/3RAwoT1SRXeZ1yQJ+TcByP2npRE7mMso083iDFLL9Jyns5VLhbfEi9TK+DIIEh5xYnp+1e+cikoVue4+LyD7LxRhG9/RuiRCzLuWW02yNJoenxvbDgbGHhDAMkCDLifhsWWd4b/CF/665i0BqiYxkrXTbxb7bBGbryBz2djv//CuVZdoxqcZnLT8uBI2Yr5oC2glU/s6KmyvacRedQPD81bq9vcDRTfzo57kgGWFFwPvY1ckROUz/WQiykBu8KUPBoOwCO0Bl+YSFNyTOHX/Z1wpdkOQ9CaZX2/tfVEzqmHoAq+ngHN8RF+oBagekFtOT/CzO5NiqMX/qQo3ZBlWOjMjSA9UyOsGKVMPKVr7ydPcdC1dI+iE/Imf4m54x22F5QAcSr5Nq+xgG0luIQffskEAzgK81cHRFo7iz2CJQEPVSjqAz0LuYTc=
    on:
      tags: true
      repo: mimiz/nodejs-event-manager
